/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    CardComponent: typeof import('./src/components/Card/CardComponent.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    OverlayBadge: typeof import('primevue/overlaybadge')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/Sidebar/SideBar.vue')['default']
    SidebarHeader: typeof import('./src/components/Sidebar/SidebarHeader.vue')['default']
    SidebarItems: typeof import('./src/components/Sidebar/SidebarItems.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
