/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/About/AboutMe.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    CardComponent: typeof import('./src/components/Card/CardComponent.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Menu: typeof import('primevue/menu')['default']
    PrePraticeComponent: typeof import('./src/components/Card/PrePraticeComponent.vue')['default']
    QuizComponent: typeof import('./src/components/Card/QuizComponent.vue')['default']
    QuizPrePraticeComponent: typeof import('./src/components/Card/QuizPrePraticeComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/Sidebar/SideBar.vue')['default']
    SidebarHeader: typeof import('./src/components/Sidebar/SidebarHeader.vue')['default']
    SidebarItems: typeof import('./src/components/Sidebar/SidebarItems.vue')['default']
  }
}
